Error Caught in x == true
AssertionError: in AssertFalseTest.chpl:7 - assertFalse failed. Given expression is True
================================================================================
